version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/database:/app/database
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "file:./database/dev.sqlite"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5000"